import { S,save,setSessionDone,vib,rewardLevelUps } from '../state.js';
import { zoneMeta } from '../util.js';
let gs={};const gameEl=document.getElementById('game'),gBody=document.getElementById('gameBody'),gTitle=document.getElementById('gameTitle'),gLevel=document.getElementById('gameLevel'),gProg=document.getElementById('gameProg'),timerFill=document.getElementById('timerFill');
export function endGame(){gameEl.classList.remove('open');if(gs.timer)clearInterval(gs.timer);if(gs.timeout)clearTimeout(gs.timeout);if(gs.rtimer)clearInterval(gs.rtimer);gs={};}
export function openGame(title){gTitle.textContent=title;gameEl.classList.add('open');gProg.style.width='0%';timerFill.style.width='100%';}
export function setProg(done,total){gProg.style.width=(done/total*100)+'%';}
export function startTimer(ms,onExpire){if(gs.rtimer)clearInterval(gs.rtimer);const t0=Date.now();timerFill.style.width='100%';gs.rExpire=onExpire;gs.rStart=t0;gs.rtimer=setInterval(()=>{const elapsed=Date.now()-t0,pct=Math.max(0,100-elapsed/ms*100);timerFill.style.width=pct+'%';if(elapsed>=ms){clearInterval(gs.rtimer);if(gs.rExpire)gs.rExpire();}},40);}
export function stopTimer(){if(gs.rtimer)clearInterval(gs.rtimer);return Date.now()-gs.rStart;}
export function adapt(key,acc){if(acc>=84)S.levels[key]=(S.levels[key]||1)+1;else if(acc<58)S.levels[key]=Math.max(1,(S.levels[key]||1)-1);}
export function completeSession(){if(setSessionDone&&!document.getElementById('protoWrap').classList.contains('unlocked')){setSessionDone(true);document.getElementById('lockState').style.display='none';document.getElementById('protoWrap').classList.add('unlocked');document.getElementById('protoTab').classList.remove('locked');document.getElementById('lockDot').style.display='none';document.getElementById('lockFill').style.width='100%';document.getElementById('lockCount').textContent='1 / 1 session';vib([10,40,20]);}}
export function finish(icon,acc,avgRtMs,zoneKey,gameKey,extraNote){if(gs.timer)clearInterval(gs.timer);if(gs.rtimer)clearInterval(gs.rtimer);setProg(1,1);gLevel.textContent='Complete';const zoneGain=Math.max(1,Math.round(acc/20)),skill=S.skills?.[gameKey==='rotation'?'spatial':gameKey],delta=skill?.history?.at(-1)?.delta||0,cqGain=Math.max(1,Math.min(12,2+Math.round(Math.max(0,delta)/5)+(acc>=85?2:0)));S.zones[zoneKey]=Math.min(100,S.zones[zoneKey]+zoneGain);S.cq+=cqGain;S.sessions++;S.bestAcc=Math.max(S.bestAcc,acc);const previous=S.best[gameKey]||0,isRecord=acc>previous&&previous>0;if(acc>previous){S.best[gameKey]=acc;if(isRecord)S.records++;}rewardLevelUps(gameKey);save();const meta=zoneMeta[zoneKey];gBody.innerHTML=`<div class="results show"><div class="results-icon">${icon}</div><div class="results-title">${acc>=78?'Challenge matched':'Calibration complete'}${isRecord?' · New best':''}</div><div class="results-stats"><div class="rst"><div class="rst-v">${acc}%</div><div class="rst-l">Accuracy</div></div><div class="rst"><div class="rst-v">${delta>=0?'+':''}${delta}</div><div class="rst-l">Rating</div></div><div class="rst"><div class="rst-v">+${cqGain}</div><div class="rst-l">CQ</div></div></div><div class="trained"><div class="trained-row"><span class="trained-dot"></span><span class="trained-zone">${meta.n}</span><span class="trained-gain">+${zoneGain}</span></div>${extraNote?`<div class="trained-row"><span class="trained-dot"></span><span class="trained-zone">${extraNote}</span></div>`:''}</div><button class="results-cta" id="resCta">Finish session</button></div>`;document.getElementById('resCta').onclick=()=>{completeSession();endGame();};vib(delta>10?[12,30,18]:[12,35,20]);}
export function bindGameShell(){document.getElementById('gameQuit').addEventListener('click',endGame);}
