import { S, vib } from '../state.js';
import { openGame, setProg, startTimer, stopTimer, finish } from './engine.js';
import { nextDifficulty, recordExperiment } from './lab.js';

function installMathStyles(){if(document.getElementById('mathChainStyles'))return;const style=document.createElement('style');style.id='mathChainStyles';style.textContent=`
.chain-reactor{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;margin:12px 0 26px}.chain-start{display:grid;place-items:center;width:68px;height:68px;flex:0 0 68px;border:1px solid oklch(82% .12 82 / .28);border-radius:50%;background:oklch(27% .07 82);color:oklch(90% .13 82);font:850 1.45rem 'JetBrains Mono',monospace}.chain-arrow{color:var(--text-3);font-weight:800}.chain-ops{display:flex;flex-wrap:wrap;justify-content:center;gap:7px}.chain-op{display:grid;place-items:center;min-width:50px;height:50px;padding:0 10px;border-radius:14px;background:oklch(28% .075 300);color:oklch(88% .06 300);font:800 .92rem 'JetBrains Mono',monospace}.chain-question{margin-bottom:8px;color:var(--text);font-size:1.45rem;font-weight:780;text-align:center}.tutorial-chain{display:flex;flex-direction:column;gap:7px;width:100%;max-width:320px;margin:4px 0 18px}.tutorial-step{display:grid;grid-template-columns:32px 1fr auto;align-items:center;gap:10px;min-height:46px;padding:7px 10px;border-radius:13px;background:oklch(21% .045 300)}.tutorial-step i{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:oklch(32% .09 300);color:oklch(88% .07 300);font-style:normal;font-weight:800}.tutorial-step span{color:var(--text-2);font:700 .78rem 'JetBrains Mono',monospace}.tutorial-step b{color:oklch(86% .13 82);font:850 .9rem 'JetBrains Mono',monospace}.math-mode{margin-bottom:7px;color:oklch(78% .12 300);font-size:.65rem;font-weight:850;letter-spacing:.11em;text-transform:uppercase}.chain-tip{display:flex;align-items:center;gap:8px;max-width:320px;margin-bottom:18px;color:var(--text-3);font-size:.68rem;line-height:1.35}.chain-tip b{color:oklch(84% .13 82);font-size:1rem}
`;document.head.appendChild(style);}
function makeChain(level){
  const steps=level<4?1:level<8?2:3;let current=4+Math.floor(Math.random()*(8+Math.min(level,5))),start=current;const operations=[];
  for(let i=0;i<steps;i+=1){const canMultiply=level>=6&&current<=24,types=['add','sub',...(canMultiply?['mul']:[])],type=types[Math.floor(Math.random()*types.length)];if(type==='add'){const n=2+Math.floor(Math.random()*(5+Math.min(level,5)));operations.push({symbol:`+${n}`});current+=n;}else if(type==='sub'){const n=1+Math.floor(Math.random()*Math.max(2,Math.min(8,current-1)));operations.push({symbol:`−${n}`});current-=n;}else{const n=2;operations.push({symbol:'×2'});current*=n;}}
  return{start,operations,answer:current};
}
function choices(answer){const values=new Set([answer]);while(values.size<4){const spread=Math.max(3,Math.round(Math.abs(answer)*.16)),candidate=answer+Math.floor(Math.random()*(spread*2+1))-spread;if(candidate!==answer&&candidate>=0)values.add(candidate);}return[...values].sort(()=>Math.random()-.5);}
export function startMath(){
  installMathStyles();openGame('Math Chain');const startedAt=Date.now(),total=10,trials=[],recent=[];let index=0,level=S.levels.math||1;const body=document.getElementById('gameBody'),levelEl=document.getElementById('gameLevel');
  function intro(){body.innerHTML=`<div class="lab-kicker">Mental arithmetic</div><div class="clear-title">Short chains, enough time</div><div class="lab-prompt">Start with one number and apply operations from left to right. Early levels have one operation; the chain grows only after stable success.</div><div class="tutorial-chain"><div class="tutorial-step"><i>1</i><span>Start</span><b>8</b></div><div class="tutorial-step"><i>2</i><span>8 + 5</span><b>13</b></div></div><div class="chain-tip"><b>✦</b><span>You now get 12–15 seconds. A mistake lowers difficulty automatically.</span></div><button class="clear-start" id="mathStart">Start calmly</button>`;document.getElementById('mathStart').onclick=round;}
  function round(){if(index>=total)return done();const chain=makeChain(level),answers=choices(chain.answer),limit=Math.max(12000,15500-level*250);setProg(index,total);levelEl.textContent=`Load ${level} · ${index+1}/${total}`;body.innerHTML=`<div class="math-mode">Chain ${index+1} of ${total}</div><div class="chain-question">Where does the number land?</div><div class="chain-reactor"><div class="chain-start">${chain.start}</div><div class="chain-arrow">→</div><div class="chain-ops">${chain.operations.map(op=>`<div class="chain-op">${op.symbol}</div>`).join('')}</div></div><div class="lab-answers">${answers.map(value=>`<button class="lab-answer" data-value="${value}">${value}</button>`).join('')}</div><div class="lab-meta"><span>${chain.operations.length} operation${chain.operations.length>1?'s':''}</span><span>${(limit/1000).toFixed(1)}s</span></div>`;let answered=false;const answer=value=>{if(answered)return;answered=true;const rt=stopTimer(),correct=value===chain.answer;trials.push({level,correct,rt,start:chain.start,operations:chain.operations.map(op=>op.symbol),answer:chain.answer});recent.push(correct);body.querySelectorAll('.lab-answer').forEach(button=>{button.disabled=true;if(+button.dataset.value===chain.answer)button.classList.add('correct');});if(!correct)body.querySelector(`[data-value="${value}"]`)?.classList.add('wrong');vib(correct?10:[24,18,24]);level=nextDifficulty(level,recent);index+=1;setTimeout(round,560);};body.querySelectorAll('.lab-answer').forEach(button=>button.onclick=()=>answer(+button.dataset.value));startTimer(limit,()=>answer(Number.NaN));}
  function done(){S.levels.math=level;const session=recordExperiment('math',trials,startedAt,level);finish('∑',session.accuracy,session.meanRtMs,'frontal','math',`Math Chain load reached ${level}.`);}intro();
}
