import { vib } from '../state.js';
import { openGame,setProg,startTimer,stopTimer,finish } from './engine.js';
import { challengeProfile,recordExperiment } from './lab.js';
const names=['a','b','c','d','e'];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function build(profile){const count=Math.min(5,2+Math.floor(Math.log2(profile.level+1)/2)),steps=Math.min(9,2+Math.floor(Math.log2(profile.level+1))),vars=names.slice(0,count),state=Object.fromEntries(vars.map(v=>[v,1+Math.floor(Math.random()*6)])),initial={...state},lines=[];for(let step=0;step<steps;step++){const next={...state},targets=shuffle(vars).slice(0,profile.level>8?Math.min(2,count):1);targets.forEach(target=>{const source=vars[Math.floor(Math.random()*vars.length)],coef=profile.level>18&&Math.random()<.3?2:1,offset=Math.floor(Math.random()*5)-2,nextValue=state[target]+state[source]*coef+offset;next[target]=Math.max(-30,Math.min(99,nextValue));lines.push(`${target} = ${target} + ${source}${coef===2?' × 2':''}${offset?` ${offset>0?'+':'−'} ${Math.abs(offset)}`:''}`);});Object.assign(state,next);}const ask=vars[Math.floor(Math.random()*vars.length)];return{initial,lines,answer:state[ask],ask,steps,count};}
function options(answer){const values=new Set([answer]);while(values.size<4){const d=1+Math.floor(Math.random()*Math.max(4,Math.abs(answer)*.14));values.add(answer+(Math.random()<.5?-d:d));}return shuffle([...values]);}
export function startStateEngine(){openGame('State Engine');const started=Date.now(),trials=[],total=8;let i=0;const body=document.getElementById('gameBody'),levelEl=document.getElementById('gameLevel');body.innerHTML=`<div class="lab-kicker">Working memory updating</div><div class="clear-title">Track a changing system</div><div class="lab-prompt">Every line uses values from the state before that line. Hold the variables, update them, discard the old state.</div><button class="cog-start" id="stateStart">Start engine</button>`;document.getElementById('stateStart').onclick=round;
 function round(){if(i>=total)return done();const p=challengeProfile('state'),q=build(p),answers=options(q.answer),limit=Math.max(7000,18000*p.speed+q.steps*850);setProg(i,total);levelEl.textContent=`Rating ${p.rating} · ${i+1}/${total}`;body.innerHTML=`<div class="lab-kicker">State ${i+1}</div><div class="state-board">${Object.entries(q.initial).map(([k,v])=>`<div class="state-cell"><span>${k}</span><b>${v}</b></div>`).join('')}</div><div class="op-list">${q.lines.map((line,index)=>`<div class="op-line">${line}<small>step ${index+1}</small></div>`).join('')}</div><div class="lab-prompt">Final value of <b>${q.ask}</b>?</div><div class="lab-answers">${answers.map(v=>`<button class="lab-answer" data-value="${v}">${v}</button>`).join('')}</div><div class="adaptive-readout"><span>Level <b>${p.level}</b></span><span>${q.count} vars</span><span>${q.steps} steps</span></div>`;const start=performance.now();let answered=false;const choose=value=>{if(answered)return;answered=true;const rt=stopTimer(),correct=Number(value)===q.answer;trials.push({correct,rt,difficulty:p.level,variables:q.count,steps:q.steps});body.querySelectorAll('.lab-answer').forEach(btn=>{btn.disabled=true;if(Number(btn.dataset.value)===q.answer)btn.classList.add('correct');});if(!correct)body.querySelector(`[data-value="${value}"]`)?.classList.add('wrong');vib(correct?8:[20,16,20]);i++;setTimeout(round,520);};body.querySelectorAll('.lab-answer').forEach(btn=>btn.onclick=()=>choose(btn.dataset.value));startTimer(limit,()=>choose('timeout'));}
 function done(){const session=recordExperiment('state',trials,started,0);finish('⌬',session.accuracy,session.medianRtMs||session.meanRtMs,'hippo','state',`State rating ${session.rating} (${session.ratingDelta>=0?'+':''}${session.ratingDelta}).`);}}
