import { S } from './state.js';
import { initEngagement } from './engagement.js';
const TAU=Math.PI*2,GOLDEN_ANGLE=Math.PI*(3-Math.sqrt(5));
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function seededNoise(index){const value=Math.sin(index*12.9898+78.233)*43758.5453;return value-Math.floor(value);}
export function makeBrainPts(count){const points=[];for(let i=0;i<count;i++){const yBase=1-2*((i+.5)/count),ring=Math.sqrt(Math.max(0,1-yBase*yBase)),angle=i*GOLDEN_ANGLE,noise=seededNoise(i);let x=Math.cos(angle)*ring*1.14,y=yBase*.84,z=Math.sin(angle)*ring*.92;const frontal=1+.08*clamp((z+.35)/1.2,0,1),rear=1-.05*clamp((-z+.55)/1.5,0,1);x*=frontal*rear;const gyri=Math.sin(angle*8+yBase*10)*.036+Math.sin(angle*15-yBase*7)*.021+Math.cos(x*12+z*8)*.014,shell=i%7===0?.82+noise*.1:.97+gyri;x*=shell;z*=shell;if(y<-.42)y=-.42+(y+.42)*.38;if(y<.02)x*=1.04+(.02-y)*.1;const cleft=.075*clamp((y+.28)/.92,0,1)*(1-Math.min(.62,Math.abs(z)*.5));x+=(x<0?-1:1)*cleft;z+=.06*(1-yBase*yBase)-.016;points.push({x,y,z,size:.68+seededNoise(i+9000)*.58,phase:seededNoise(i+12000)*TAU,core:i%9===0});}return points;}
export function mountStatBrain(){
  const canvas=document.getElementById('brainCanvas');if(!canvas)return;initEngagement();const context=canvas.getContext('2d'),width=canvas.width,height=canvas.height,points=makeBrainPts(1500),centerX=width/2,centerY=height/2-2,scale=114,pitch=-.12,pitchCos=Math.cos(pitch),pitchSin=Math.sin(pitch),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,speed=reduced?.00005:.00027;let started=performance.now(),paused=0,evolutionPulse=0;
  window.addEventListener('brain:evolved',()=>{evolutionPulse=1;});
  function draw(now){
    const tier=S.neurons?.evolution||0,rotation=(now-started)*speed,rc=Math.cos(rotation),rs=Math.sin(rotation),visible=900+tier*180,breath=1+Math.sin(now*.0014)*(.006+tier*.002);context.clearRect(0,0,width,height);
    if(tier>=2){const coreRadius=18+tier*5+Math.sin(now*.002)*2,core=context.createRadialGradient(centerX,centerY,0,centerX,centerY,coreRadius);core.addColorStop(0,`oklch(88% .1 282 / ${.1+tier*.035})`);core.addColorStop(.45,`oklch(72% .15 300 / ${.08+tier*.025})`);core.addColorStop(1,'transparent');context.fillStyle=core;context.beginPath();context.arc(centerX,centerY,coreRadius,0,TAU);context.fill();}
    const projected=points.slice(0,visible).map((p,index)=>{const px=p.x*breath,pz=p.z*breath,x=px*rc-pz*rs,z=px*rs+pz*rc,y=p.y*pitchCos-z*pitchSin,depth=p.y*pitchSin+z*pitchCos,perspective=3.65/(3.65-depth);return{x:centerX+x*scale*perspective,y:centerY-y*scale*perspective,depth,perspective,size:p.size,phase:p.phase,core:p.core,index};}).sort((a,b)=>a.depth-b.depth);
    projected.forEach(p=>{const depth=clamp((p.depth+1.12)/2.24,0,1),front=Math.pow(depth,1.3),pulse=tier?Math.max(0,Math.sin(now*.0018+p.phase))*tier*.08:0,radius=(.58+depth*1.16+tier*.04)*p.size*p.perspective,hue=300-depth*12+(tier>=1&&p.core?(-22):0),alpha=.14+depth*.76+pulse;context.beginPath();context.arc(p.x,p.y,radius,0,TAU);context.fillStyle=`oklch(${50+depth*36+tier*1.2}% ${.1+depth*.095+tier*.008} ${hue} / ${Math.min(.98,alpha)})`;context.fill();if(tier>=3&&p.core&&p.index%4===0&&front>.58){context.fillStyle=`oklch(88% .1 282 / ${.12+front*.18})`;context.beginPath();context.arc(p.x,p.y,radius*.48,0,TAU);context.fill();}});
    if(evolutionPulse>0){context.strokeStyle=`oklch(84% .11 282 / ${evolutionPulse*.45})`;context.lineWidth=1.5;context.beginPath();context.arc(centerX,centerY,(1-evolutionPulse)*92+24,0,TAU);context.stroke();evolutionPulse=Math.max(0,evolutionPulse-.018);}
    if(tier>=3&&Math.floor(now/1400)%7===0){const spark=(now%1400)/1400;if(spark<.2){context.fillStyle=`oklch(91% .08 282 / ${(.2-spark)*2})`;for(let i=0;i<5;i++){const a=i*TAU/5+rotation,r=58+spark*90;context.beginPath();context.arc(centerX+Math.cos(a)*r,centerY+Math.sin(a)*r*.58,1.1,0,TAU);context.fill();}}}
    requestAnimationFrame(draw);
  }
  document.addEventListener('visibilitychange',()=>{if(document.hidden)paused=performance.now();else if(paused){started+=performance.now()-paused;paused=0;}});requestAnimationFrame(draw);
}
