// Symmetric front-facing point brain. Expensive artwork is cached once;
// every frame only composites it and draws six lightweight impulses.
const TAU=Math.PI*2,brains=[];let raf=0;
function seeded(seed=29){return()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296)}
function xLimit(y){const top=Math.max(0,1-Math.pow((y+.02)/1.04,2));const base=.93*Math.sqrt(top),crown=.10*Math.exp(-Math.pow((y+.64)/.24,2)),temple=.07*Math.exp(-Math.pow((y-.05)/.34,2)),taper=y>.5?1-(y-.5)*.28:1;return Math.max(.18,(base+crown+temple)*taper)}
function inside(x,y){if(y<-.91||y>.92)return false;const notch=y<-.62?.055*(1-(y+.91)/.29):0;return Math.abs(x)<xLimit(y)&&Math.abs(x)>notch}
function makeGeometry(){const rnd=seeded(),points=[],paths=[];const add=samples=>{const path=[];for(const[x,y]of samples){if(!inside(x,y))continue;path.push(points.length);points.push({x,y,r:.75+rnd()*.85,a:.46+rnd()*.42})}if(path.length>2)paths.push(path)};
 for(const side of[-1,1]){const edge=[];for(let i=0;i<=62;i++){const y=-.88+i*(1.76/62),r=.018*Math.sin(i*1.7)+.012*Math.sin(i*3.1);edge.push([side*(xLimit(y)+r),y])}add(edge)}
 const fissure=[];for(let i=0;i<42;i++){const y=-.84+i*.039;fissure.push([.018*Math.sin(i*.82)*(.35+(y+.84)*.42),y])}add(fissure);
 for(const side of[-1,1]){for(let band=0;band<8;band++){const row=[],y0=-.67+band*.19;for(let i=0;i<34;i++){const u=i/33,span=xLimit(y0)*.90,x=side*(.08+u*Math.max(.1,span-.08)),y=y0+Math.sin(u*Math.PI*(2.1+(band%3)*.45)+band*.72)*(.045+band*.002);row.push([x,y])}add(row)}for(let col=0;col<4;col++){const fold=[];for(let i=0;i<27;i++){const u=i/26,y=-.72+u*1.42,x=side*(.22+col*.17+Math.sin(u*Math.PI*3+col)*.045);fold.push([x,y])}add(fold)}}
 for(let i=0;i<115;i++){let x,y;do{x=rnd()*1.9-.95;y=rnd()*1.78-.89}while(!inside(x,y));points.push({x,y,r:.55+rnd()*.65,a:.18+rnd()*.28})}return{points,paths}}
const GEO=makeGeometry();
function active(b){if(document.hidden||!b.canvas.isConnected)return false;const mode=document.getElementById('mindView')?.dataset.mode||'stats';return b.id==='brainCanvas'?mode==='stats':mode==='stack'}
function cacheBrain(b){const{w,h,scale}=b,cache=document.createElement('canvas');cache.width=w;cache.height=h;const c=cache.getContext('2d',{alpha:true}),s=Math.min(w/2.12,h/2.02)*scale,ox=w/2,oy=h/2+h*.015,xy=p=>[ox+p.x*s,oy+p.y*s];c.lineCap='round';c.lineJoin='round';c.strokeStyle='oklch(75% 0.10 300 / 0.13)';c.lineWidth=Math.max(.55,s*.006);for(const path of GEO.paths){c.beginPath();path.forEach((idx,i)=>{const[x,y]=xy(GEO.points[idx]);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}c.shadowColor='oklch(82% 0.11 300 / 0.52)';c.shadowBlur=Math.max(3,s*.035);for(const p of GEO.points){const[x,y]=xy(p);c.fillStyle=`oklch(86% 0.105 300 / ${p.a})`;c.beginPath();c.arc(x,y,p.r*Math.max(.9,s*.012),0,TAU);c.fill()}c.shadowBlur=0;b.cache=cache;b.xy=xy;b.routes=GEO.paths.filter(p=>p.length>12);b.impulses=Array.from({length:6},(_,i)=>({route:(i*5)%b.routes.length,t:i/6,speed:.055+(i%3)*.011}))}
function draw(b,time,dt){const c=b.ctx;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,b.w,b.h);const breathe=1+Math.sin(time*.00105)*.006;c.save();c.translate(b.w/2,b.h/2);c.scale(breathe,breathe);c.translate(-b.w/2,-b.h/2);c.drawImage(b.cache,0,0);c.restore();c.globalCompositeOperation='lighter';c.lineCap='round';for(const pulse of b.impulses){pulse.t=(pulse.t+dt*pulse.speed)%1;const route=b.routes[pulse.route],at=pulse.t*(route.length-1),idx=Math.min(route.length-2,Math.floor(at)),mix=at-idx,p0=b.xy(GEO.points[route[idx]]),p1=b.xy(GEO.points[route[idx+1]]),x=p0[0]+(p1[0]-p0[0])*mix,y=p0[1]+(p1[1]-p0[1])*mix,tail=b.xy(GEO.points[route[Math.max(0,idx-3)]]);c.strokeStyle='oklch(87% 0.11 300 / 0.34)';c.lineWidth=2;c.beginPath();c.moveTo(tail[0],tail[1]);c.lineTo(x,y);c.stroke();c.shadowColor='oklch(92% 0.10 300 / 0.82)';c.shadowBlur=7;c.fillStyle='oklch(96% 0.06 300 / 0.95)';c.beginPath();c.arc(x,y,2.1,0,TAU);c.fill()}c.shadowBlur=0;c.globalCompositeOperation='source-over'}
function tick(time){const dt=Math.min(.033,(time-(tick.last||time))/1000);tick.last=time;for(const b of brains)if(active(b))draw(b,time,dt);raf=requestAnimationFrame(tick)}
export function makeBrainPts(){return[]}
export function mountBrain(id,opt={}){const canvas=document.getElementById(id);if(!canvas||brains.some(b=>b.canvas===canvas))return;const b={id,canvas,ctx:canvas.getContext('2d',{alpha:true,desynchronized:true}),w:canvas.width,h:canvas.height,scale:opt.scale||1};cacheBrain(b);brains.push(b);if(!raf)raf=requestAnimationFrame(tick)}
