const style=document.createElement('style');
style.id='brainmaxAuthoredProduct';
style.textContent=`
:root{
  --radius-control:10px;
  --radius-panel:14px;
  --line:oklch(80% .045 295 / .14);
  --matte:oklch(17.5% .038 300);
  --matte-raised:oklch(21.5% .045 300);
}
body::after{display:none!important;content:none!important}
.aurora-blob{opacity:.18!important;filter:blur(130px)!important;animation:none!important}.ab1{transform:translate(-70px,-80px)!important}.ab2{transform:translate(80px,30px)!important}.ab3{opacity:.08!important}
*{text-shadow:none!important}.phone{border-inline:1px solid oklch(78% .04 300 / .05)}
.header{padding-top:calc(var(--safe-t) + 18px)!important}.h-context{font-size:.65rem!important;letter-spacing:.16em!important}.h-age{font-family:'JetBrains Mono',monospace!important;font-size:.68rem!important;font-weight:600!important;color:var(--blend)!important}
.screen-head{padding-top:28px!important}.screen-title{font-size:2.35rem!important;font-weight:720!important;letter-spacing:-.055em!important}.screen-sub{max-width:34ch;font-size:.8rem!important;line-height:1.45}
.tabbar{background:oklch(12% .03 300)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;border-color:var(--line)!important}.tab.active::before{display:none!important}.tab.active svg{filter:none!important;transform:none!important}.tab{gap:6px!important}.tab-l{font-size:.52rem!important;letter-spacing:.06em;text-transform:uppercase}
.stats-mode-switch{padding:2px!important;border-radius:12px!important;background:var(--matte)!important;box-shadow:none!important}.stats-mode-switch button{min-height:34px!important;border-radius:9px!important;text-transform:uppercase;letter-spacing:.08em;font-size:.62rem!important}.stats-mode-switch button.active{box-shadow:none!important}
.constellation{height:460px!important}.brain-center{top:53%!important}.coin-chip{top:48px!important;border-radius:8px!important;background:var(--matte)!important;box-shadow:none!important}.node-v{font-family:'JetBrains Mono',monospace!important;font-size:1.35rem!important}.node-l{font-size:.5rem!important;letter-spacing:.1em!important}.bc-cq{font-family:'JetBrains Mono',monospace!important;font-size:2.15rem!important}.bc-lbl,.sb-lbl{letter-spacing:.18em!important}
.glow-btn{padding:0!important;border-radius:12px!important;background:none!important;border:1px solid color-mix(in oklab,var(--blend) 28%,transparent)!important}.glow-btn::after,.gb-inner::before{display:none!important}.gb-inner{border-radius:11px!important;background:var(--matte-raised)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;text-align:left;padding:17px 18px!important}.gb-sub{margin-top:5px!important}
.tc-wrap{justify-content:flex-start!important;padding-top:24px}.tc-slide{padding:0 8px!important}.tc-slide:not(.active){opacity:.28!important;transform:scale(.94)!important}.tc-big{min-height:292px!important;border-radius:14px!important;padding:22px!important;background:var(--matte-raised)!important;border-color:var(--line)!important;box-shadow:none!important}.tc-big::before{width:110px!important;height:110px!important;top:-42px!important;right:-35px!important;opacity:.38;animation:none!important}.tc-big::after{display:none!important}.tc-slide{counter-increment:lab}.tc-track{counter-reset:lab}.tc-lvl{top:20px!important;right:18px!important;border:0!important;border-radius:0!important;background:none!important;padding:0!important;font-size:.62rem!important;color:var(--text-3)!important}.tc-lvl::before{content:'LAB 0' counter(lab) ' / ';color:var(--card-accent)}.tc-emoji{font-size:2.25rem!important}.tc-name{font-size:1.85rem!important;line-height:1!important;max-width:10ch}.tc-zone{font-size:.62rem!important}.tc-play{border-radius:9px!important;box-shadow:none!important;padding:11px 16px!important;font-size:.78rem!important}.tc-explain{margin-top:18px!important;border-radius:0!important;border:0!important;border-top:1px solid var(--line)!important;background:none!important;padding:14px 2px 0!important}.tc-dots{padding-top:14px!important}.tc-dot{width:18px!important;height:2px!important;border-radius:0!important}.tc-dot.on{width:32px!important}
.stack-const{height:420px!important}.snode-badge{border-radius:50%!important;backdrop-filter:none!important;box-shadow:none!important}.stack-eff{border-block:1px solid var(--line);padding:14px 0}.stack-add{border-radius:10px!important;border-style:solid!important}.eff-v{font-family:'JetBrains Mono',monospace!important}.eff-l{letter-spacing:.1em!important}
.lock-icon{width:56px!important;height:56px!important;border-radius:12px!important;backdrop-filter:none!important}.lock-title{font-family:'Bricolage Grotesque',system-ui,sans-serif!important;font-weight:700!important}.lock-bar{height:3px!important}.proto-item{padding:17px 0!important}.proto-check{border-radius:6px!important;box-shadow:none!important}
.map-circ{border-radius:14px!important;backdrop-filter:none!important;box-shadow:none!important}.map-circ.unlocked,.map-node:nth-child(odd) .map-circ.unlocked{box-shadow:none!important}.map-node:nth-child(3n+2) .map-circ{border-radius:50%!important}.map-node:nth-child(3n) .map-circ{border-radius:22px 8px 22px 8px!important}
.reader-top{background:var(--matte)!important}.reader-body{padding-top:32px!important}.reader-tier{font-family:'JetBrains Mono',monospace;font-size:.6rem!important;letter-spacing:.14em!important}.reader-h1{font-size:2rem!important;line-height:1.08!important;max-width:14ch}.reader-meta{padding-bottom:18px;border-bottom:1px solid var(--line)}.reader-body .callout{border-radius:10px!important;background:var(--matte-raised)!important}
.game{background:var(--bg)!important}.game-top{padding-top:calc(var(--safe-t) + 15px)!important}.game-quit{font-size:1.25rem!important}.game-title{font-size:.78rem!important;letter-spacing:.04em}.timer-bar,.game-progress{border-radius:0!important;height:2px!important}.timer-fill,.game-progress-fill{border-radius:0!important}.game-body{justify-content:flex-start!important;padding-top:44px!important}.game-body>*{animation-duration:.28s!important}.cog-title,.clear-title{font-size:1.75rem!important;letter-spacing:-.04em;max-width:13ch!important}.cog-copy,.lab-prompt{font-size:.8rem!important}.lab-kicker,.step-tag,.math-mode{font-family:'JetBrains Mono',monospace!important;font-size:.58rem!important;letter-spacing:.14em!important}
.lab-answer,.color-answer,.go-button,.confidence button,.creative-actions button,.rot-btn,.stroop-btn,.ct-btn,.clear-start,.cog-start,.results-cta,.idea-add,.cr-send{border-radius:10px!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.lab-answer,.color-answer{min-height:56px!important}.clear-face,.number-face{border-radius:0!important}.move-pill,.face-key,.dual-face-key,.tutorial-step,.memory-pair,.assoc-words span,.idea-chip{border-radius:8px!important}.chain-start{border-radius:12px!important}.chain-op{border-radius:8px!important}.rule-badge{border-radius:6px!important}
.results{text-align:left!important;align-items:stretch!important;max-width:340px}.results-icon{font-size:2.6rem!important;margin-bottom:22px!important}.results-title{font-family:'Bricolage Grotesque',system-ui,sans-serif!important;font-size:2rem!important;font-weight:720!important}.results-stats{justify-content:space-between;border-block:1px solid var(--line);padding:16px 0;margin:12px 0 20px!important}.rst{text-align:left!important}.rst-v{font-family:'JetBrains Mono',monospace!important;font-size:1.5rem!important}.trained{border-radius:10px!important;background:var(--matte)!important;padding:16px!important}.results-cta{max-width:none!important}
.modal{border-radius:18px 18px 0 0!important}.modal-h{font-family:'Bricolage Grotesque',system-ui,sans-serif!important;font-weight:720!important}.compound-opt{padding:17px 0!important}
button{filter:none!important}button:active{transform:scale(.98)!important}.lab-answer.correct,.color-answer.correct,.rot-btn.correct,.stroop-btn.correct{animation:none!important;box-shadow:none!important}
@media(min-width:700px){.phone{max-width:520px!important}.view{padding-inline:32px!important}}
`;
document.head.appendChild(style);
