const style=document.createElement('style');
style.id='brainmaxBrandSystem';
style.textContent=`
:root{--moon:oklch(84% .09 225);--moon-soft:oklch(68% .08 235);--violet:oklch(80% .12 300);--ink-surface:oklch(19% .045 300);--ink-raised:oklch(24% .055 300)}
.phone::before{content:'';position:absolute;inset:74px 12px 84px;z-index:-1;pointer-events:none;border-radius:42% 58% 46% 54% / 52% 38% 62% 48%;border:1px solid oklch(83% .08 225 / .07);transform:rotate(-8deg);box-shadow:0 0 90px oklch(70% .1 225 / .04),inset 0 0 80px oklch(70% .12 300 / .03)}
.header{position:relative}.header::after{content:'';position:absolute;left:24px;right:24px;bottom:-2px;height:1px;background:linear-gradient(90deg,var(--section-accent),transparent 42%);opacity:.28;transform-origin:left;animation:headerTrace .7s cubic-bezier(.16,1,.3,1) both}
.h-age{color:var(--moon);text-shadow:0 0 18px oklch(76% .09 225 / .18)}
.stats-mode-switch{background:var(--ink-surface)!important;border-color:oklch(80% .08 300 / .2)!important;box-shadow:0 16px 36px oklch(7% .02 300 / .28)!important}.stats-mode-switch button.active{background:var(--violet)!important;color:oklch(17% .035 300)!important}.view[data-view="stack"] .stats-mode-switch button.active{background:var(--moon)!important}
.constellation::before,.stack-const::before{content:'';position:absolute;left:50%;top:52%;width:220px;height:220px;border:1px solid oklch(82% .08 225 / .1);border-radius:50%;transform:translate(-50%,-50%) rotate(12deg);clip-path:polygon(0 0,100% 0,100% 64%,64% 64%,64% 100%,0 100%);pointer-events:none;animation:fieldTurn 18s linear infinite}.constellation::after,.stack-const::after{content:'';position:absolute;left:50%;top:52%;width:168px;height:168px;border:1px solid oklch(80% .11 300 / .1);border-radius:38% 62% 52% 48%;transform:translate(-50%,-50%) rotate(-16deg);pointer-events:none;animation:fieldTurnReverse 14s linear infinite}
.bc-cq{background:none!important;-webkit-background-clip:initial!important;background-clip:initial!important;color:var(--violet)!important}.sb-syn{color:var(--moon)!important}.node:nth-of-type(even) .node-v,.eff-item:nth-child(2) .eff-v{color:var(--moon)!important;text-shadow:0 0 16px oklch(76% .09 225 / .38)!important}
.glow-btn{background:linear-gradient(130deg,var(--violet),oklch(66% .1 225),oklch(31% .06 300))!important}.gb-inner{background:var(--ink-surface)!important}.gb-inner::before{background:linear-gradient(115deg,transparent 36%,oklch(92% .04 225 / .14) 50%,transparent 64%)!important}
.stack-add{background:var(--ink-surface)!important;border:1px solid oklch(78% .08 225 / .16)!important}.stack-add::first-letter{color:var(--moon)}.snode:nth-of-type(even) .snode-badge{color:var(--moon)!important;box-shadow:0 0 18px oklch(76% .09 225 / .24)!important}
.lock-icon{background:var(--ink-surface)!important;border-color:oklch(80% .08 225 / .16)!important}.lock-icon svg{stroke:var(--moon)!important}.lock-fill{background:linear-gradient(90deg,var(--violet),var(--moon))!important}.lock-hint{color:var(--moon)!important}.proto-item{border-color:oklch(80% .06 300 / .12)!important}.proto-check.on{background:var(--moon)!important;border-color:var(--moon)!important;box-shadow:0 0 18px oklch(78% .1 225 / .3)!important}
.map-circ{background:var(--ink-surface);backdrop-filter:none!important}.map-circ.unlocked{background:var(--ink-raised)!important;border-color:oklch(82% .09 225 / .3)!important;box-shadow:0 0 0 5px oklch(68% .1 300 / .06),0 0 28px oklch(72% .09 225 / .24)!important}.map-node:nth-child(odd) .map-circ.unlocked{border-color:oklch(82% .11 300 / .3)!important;box-shadow:0 0 0 5px oklch(72% .09 225 / .05),0 0 28px oklch(72% .12 300 / .24)!important}.map-nm{font-weight:700!important}
.reader{background:var(--bg)!important}.reader-top{background:var(--ink-surface);border-color:oklch(80% .07 225 / .12)!important}.reader-back,.reader-tier{color:var(--moon)!important}.reader-h1{font-family:'Bricolage Grotesque',system-ui,sans-serif!important;font-weight:750!important;letter-spacing:-.035em!important}.reader-body .callout{position:relative;background:var(--ink-surface)!important;border-color:oklch(80% .08 225 / .16)!important}.reader-body .callout::before{content:'✦';display:inline-block;margin-right:8px;color:var(--moon)}
.game{background:radial-gradient(circle at 50% 22%,oklch(21% .06 300),var(--bg) 42%)!important}.game-top{position:relative}.game-top::after{content:'';position:absolute;left:24px;right:24px;bottom:4px;height:1px;background:linear-gradient(90deg,var(--violet),var(--moon),transparent);opacity:.22}.game-title{font-family:'Bricolage Grotesque',system-ui,sans-serif!important;font-weight:750!important}.game-level{color:var(--moon)!important}.timer-fill,.game-progress-fill{background:linear-gradient(90deg,var(--violet),var(--moon))!important}.lab-kicker,.step-tag,.rule-badge,.math-mode{color:var(--moon)!important}.lab-answer,.color-answer,.go-button,.confidence button,.creative-actions button,.rot-btn,.stroop-btn,.ct-btn{background:var(--ink-raised)!important;border-color:oklch(80% .07 300 / .18)!important;box-shadow:inset 0 1px 0 oklch(90% .03 300 / .05)}.lab-answer:nth-child(even),.color-answer:nth-child(even){border-color:oklch(80% .08 225 / .18)!important}.lab-answer.correct,.color-answer.correct,.rot-btn.correct,.stroop-btn.correct{background:oklch(34% .1 225)!important;border-color:var(--moon)!important;color:oklch(91% .06 225)!important}.clear-start,.cog-start,.results-cta{background:var(--violet)!important;color:oklch(17% .035 300)!important;box-shadow:0 16px 34px -18px oklch(72% .16 300 / .7)!important}.idea-add,.cr-send{background:var(--moon)!important;color:oklch(17% .035 300)!important}.trained{background:var(--ink-surface)!important;backdrop-filter:none!important;border-color:oklch(80% .08 225 / .14)!important}.trained-dot:nth-of-type(even){background:var(--moon)!important}.trained-gain,.trained-lvl{color:var(--moon)!important}.results-icon{color:var(--moon);text-shadow:0 0 26px oklch(78% .1 225 / .28)}
.modal{background:var(--ink-surface)!important;backdrop-filter:none!important}.compound-opt{border-color:oklch(80% .06 300 / .12)!important}.compound-opt:nth-child(even) .co-add{color:var(--moon)!important}
.tabbar::before{content:'';position:absolute;top:-42px;left:50%;width:180px;height:64px;transform:translateX(-50%);background:radial-gradient(ellipse,oklch(69% .1 225 / .08),transparent 70%);pointer-events:none}.tab.active{color:var(--section-accent,var(--violet))!important}
@keyframes headerTrace{from{opacity:0;transform:scaleX(.15)}to{opacity:.28;transform:scaleX(1)}}@keyframes fieldTurn{to{transform:translate(-50%,-50%) rotate(372deg)}}@keyframes fieldTurnReverse{to{transform:translate(-50%,-50%) rotate(-376deg)}}
@media(prefers-reduced-motion:reduce){.constellation::before,.constellation::after,.stack-const::before,.stack-const::after{animation:none!important}}
`;
document.head.appendChild(style);
