import { S, settleNeurons, neuronRate, buyEvolution, vib } from './state.js';
import { goTo } from './nav.js';
const STACK_POSITIONS=[[16,24],[84,24],[16,80],[84,80],[50,10],[50,90]];
const EVOLUTIONS=[{tier:1,name:'Synaptic Bloom',cost:180,note:'Denser cortex + living nuclei'},{tier:2,name:'Axon Veil',cost:650,note:'Inner signal field + moonlight depth'},{tier:3,name:'Crown Cortex',cost:1800,note:'Double shell + rare neural flare'}];
function injectStyles(){const style=document.createElement('style');style.textContent=`
.tab[data-v="2"]{display:none}.view[data-view="stats"],.view[data-view="stack"]{position:relative;padding-top:8px!important}.view[data-view="stack"] .screen-head{display:none}
.stats-toolbar{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:10px;width:min(100%,390px);min-height:44px;margin:4px auto 0;padding:5px 5px 5px 7px;border:1px solid var(--line);border-radius:12px;background:var(--matte);position:relative;z-index:12}
.stats-mode-switch{display:grid;grid-template-columns:1fr 1fr;gap:2px;min-width:0;padding:2px;border-radius:9px;background:oklch(14.5% .032 300)}.stats-mode-switch button{min-width:0;min-height:32px;padding:0 13px;border:0;border-radius:7px;background:transparent;color:var(--text-3);font-size:.59rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.stats-mode-switch button.active{background:var(--blend);color:oklch(17% .035 300)}
.neuron-bank{display:grid;grid-template-columns:auto auto;align-items:center;column-gap:7px;min-width:96px;min-height:34px;padding:4px 7px;border:0;border-left:1px solid var(--line);border-radius:0;background:transparent;font-family:'JetBrains Mono',monospace;cursor:pointer}.neuron-bank::before{content:'✦';grid-row:1/3;color:var(--blend);font-size:.75rem}.neuron-value{color:var(--text);font-size:.68rem;font-weight:700;font-variant-numeric:tabular-nums}.neuron-rate{color:var(--text-3);font-size:.46rem;letter-spacing:.03em}.neuron-bank:active{transform:scale(.985)}
.constellation,.stack-const{margin-top:0!important}.evolution-panel{display:none;width:min(100%,390px);margin:8px auto 18px;padding:15px 14px 0;border:1px solid var(--line);border-radius:12px;background:var(--matte)}.evolution-panel.open{display:block;animation:evoOpen 280ms cubic-bezier(.16,1,.3,1) both}.evolution-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:10px}.evolution-head b{font-size:.9rem}.evolution-head span{color:var(--text-3);font:.56rem 'JetBrains Mono',monospace;text-transform:uppercase;letter-spacing:.08em}.evolution-row{display:grid;grid-template-columns:28px minmax(0,1fr) auto;align-items:center;gap:10px;padding:11px 0;border-bottom:1px solid var(--line)}.evolution-row:last-child{border-bottom:0}.evolution-index{color:var(--blend);font:.62rem 'JetBrains Mono',monospace}.evolution-copy b{display:block;font-size:.78rem}.evolution-copy small{display:block;margin-top:2px;color:var(--text-3);font-size:.62rem}.evolution-buy{min-width:72px;min-height:36px;border:1px solid color-mix(in oklab,var(--blend) 25%,transparent);border-radius:8px;background:var(--matte-raised);color:var(--blend);font:.62rem 'JetBrains Mono',monospace}.evolution-buy[disabled]{opacity:.38}.evolution-buy.owned{border-color:transparent;background:transparent;color:var(--text-3)}
.stack-const canvas#stackLines{display:none}.stack-const{height:430px}.stack-brain{top:52%;z-index:3}#stackBrain{width:174px;height:158px}.stack-flow{position:absolute;inset:0;z-index:2;width:100%;height:100%;pointer-events:none}.snode{z-index:4}.evolution-flash{position:fixed;left:50%;top:43%;z-index:110;transform:translate(-50%,-50%);color:var(--blend);font:700 .68rem 'JetBrains Mono',monospace;letter-spacing:.12em;text-transform:uppercase;pointer-events:none;animation:evoFlash 1.1s cubic-bezier(.16,1,.3,1) forwards}
@keyframes evoOpen{from{opacity:0;transform:translateY(-6px)}to{opacity:1;transform:translateY(0)}}@keyframes evoFlash{0%{opacity:0;transform:translate(-50%,-35%)}25%{opacity:1}100%{opacity:0;transform:translate(-50%,-85%)}}
@media(max-width:360px){.stats-toolbar{gap:6px}.stats-mode-switch button{padding-inline:9px}.neuron-bank{min-width:84px;padding-inline:5px}.evolution-panel{padding-inline:10px}}
`;document.head.appendChild(style);}
function createToolbar(view,active){const toolbar=document.createElement('div');toolbar.className='stats-toolbar';toolbar.innerHTML=`<div class="stats-mode-switch"><button data-mode="brain" class="${active==='brain'?'active':''}">Brain</button><button data-mode="stack" class="${active==='stack'?'active':''}">Stack</button></div><button class="neuron-bank" aria-expanded="false"><span class="neuron-value">0</span><span class="neuron-rate">+0/h</span></button>`;toolbar.querySelector('[data-mode="brain"]').onclick=()=>goTo(0);toolbar.querySelector('[data-mode="stack"]').onclick=()=>goTo(2);view.prepend(toolbar);return toolbar;}
const format=value=>Math.floor(value).toLocaleString();
function initNeuronEconomy(toolbars){const brainView=document.querySelector('.view[data-view="stats"]'),constellation=brainView?.querySelector('.constellation');if(!brainView||!constellation)return;settleNeurons();const panel=document.createElement('section');panel.className='evolution-panel';panel.innerHTML='<div class="evolution-head"><b>Brain evolution</b><span>Cosmetic only</span></div><div class="evolution-list"></div>';toolbars[0].insertAdjacentElement('afterend',panel);const banks=toolbars.map(toolbar=>toolbar.querySelector('.neuron-bank'));const render=()=>{settleNeurons();banks.forEach(bank=>{bank.querySelector('.neuron-value').textContent=format(S.neurons.balance);bank.querySelector('.neuron-rate').textContent=`+${Math.round(neuronRate()*3600)}/h`;});panel.querySelector('.evolution-list').innerHTML=EVOLUTIONS.map(item=>{const owned=S.neurons.evolution>=item.tier,next=S.neurons.evolution+1===item.tier,can=next&&S.neurons.balance>=item.cost;return `<div class="evolution-row"><span class="evolution-index">0${item.tier}</span><span class="evolution-copy"><b>${item.name}</b><small>${item.note}</small></span><button class="evolution-buy ${owned?'owned':''}" data-tier="${item.tier}" ${!can?'disabled':''}>${owned?'Owned':format(item.cost)+' ✦'}</button></div>`;}).join('');panel.querySelectorAll('.evolution-buy:not(.owned)').forEach(button=>button.onclick=()=>{const item=EVOLUTIONS.find(x=>x.tier===+button.dataset.tier);if(item&&buyEvolution(item.tier,item.cost)){vib([10,35,18,35,24]);const flash=document.createElement('div');flash.className='evolution-flash';flash.textContent=item.name+' unlocked';document.body.appendChild(flash);flash.onanimationend=()=>flash.remove();render();}});};banks.forEach(bank=>bank.onclick=()=>{panel.classList.toggle('open');banks.forEach(item=>item.setAttribute('aria-expanded',String(panel.classList.contains('open'))));});render();setInterval(render,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});}
function applyStackPositions(){document.querySelectorAll('.stack-const .snode').forEach((node,index)=>{const pos=STACK_POSITIONS[index]||[50+Math.cos(index)*36,50+Math.sin(index)*38];node.style.left=pos[0]+'%';node.style.top=pos[1]+'%';});}
function initStackFlow(){const host=document.querySelector('.stack-const');if(!host)return;const canvas=document.createElement('canvas');canvas.className='stack-flow';host.appendChild(canvas);const context=canvas.getContext('2d'),particles=Array.from({length:18},(_,index)=>({target:index,phase:Math.random(),speed:.025+Math.random()*.025,bend:(Math.random()-.5)*70,size:.7+Math.random()}));function resize(){canvas.width=host.offsetWidth;canvas.height=host.offsetHeight;}function draw(now){const nodes=[...host.querySelectorAll('.snode')];context.clearRect(0,0,canvas.width,canvas.height);if(nodes.length){const start={x:canvas.width/2,y:canvas.height*.52};particles.forEach(p=>{const node=nodes[p.target%nodes.length],end={x:node.offsetLeft,y:node.offsetTop},raw=((now/1000)*p.speed+p.phase)%1,t=raw*raw*(3-2*raw),back=1-t,control={x:(start.x+end.x)/2+p.bend,y:(start.y+end.y)/2-18},x=back*back*start.x+2*back*t*control.x+t*t*end.x,y=back*back*start.y+2*back*t*control.y+t*t*end.y,alpha=Math.min(1,raw*5,(1-raw)*5)*.55;context.beginPath();context.arc(x,y,p.size,0,Math.PI*2);context.fillStyle=`oklch(82% .1 282 / ${alpha})`;context.fill();});}requestAnimationFrame(draw);}new MutationObserver(applyStackPositions).observe(host,{childList:true});applyStackPositions();resize();window.addEventListener('resize',resize);requestAnimationFrame(draw);}
export function initEngagement(){if(document.documentElement.dataset.engagementReady)return;document.documentElement.dataset.engagementReady='true';injectStyles();const toolbars=[createToolbar(document.querySelector('.view[data-view="stats"]'),'brain'),createToolbar(document.querySelector('.view[data-view="stack"]'),'stack')];initNeuronEconomy(toolbars);initStackFlow();}
