import { articles } from './data/articles.js';
import { S } from './state.js';
import { openArticle, isUnlocked } from './reader.js';
const mapVp=document.getElementById('mapVp');
const mapWorld=document.getElementById('mapWorld');
let mapScale=0.6,mapX=0,mapY=0,mdrag=false,mlx=0,mly=0,pinch=false,pd0=0,ps0=1;
export function drawMapLines(){const cv=document.getElementById('mapLines'),cx=cv.getContext('2d');cx.clearRect(0,0,900,900);cx.lineWidth=2;const center=articles[0];articles.forEach((a,i)=>{if(i===0)return;const un=isUnlocked(a);cx.strokeStyle=un?'oklch(70% 0.2 300 / 0.4)':'oklch(40% 0.05 300 / 0.3)';cx.shadowBlur=un?8:0;cx.shadowColor='oklch(72% 0.24 300 / 0.5)';const bxc=(center.x+a.x)/2+(a.y-center.y)*0.2,byc=(center.y+a.y)/2-(a.x-center.x)*0.2;cx.beginPath();cx.moveTo(center.x,center.y);cx.quadraticCurveTo(bxc,byc,a.x,a.y);cx.stroke();});cx.shadowBlur=0;}
export function renderMap(){mapWorld.querySelectorAll('.map-node').forEach(n=>n.remove());drawMapLines();articles.forEach((a,i)=>{const un=isUnlocked(a);const el=document.createElement('div');el.className='map-node';el.style.left=a.x+'px';el.style.top=a.y+'px';el.innerHTML=`<div class="map-circ ${un?'unlocked':'locked'}">${un?a.emoji:'🔒'}</div><div class="map-nm">${un?a.t:'Locked'}</div>`;if(un)el.onclick=()=>openArticle(i);mapWorld.appendChild(el);});}
export function applyMapTransform(){mapWorld.style.transform=`translate(${mapX}px,${mapY}px) scale(${mapScale})`;}
export function centerMap(){const vw=mapVp.offsetWidth,vh=mapVp.offsetHeight;mapScale=0.55;mapX=vw/2-450*mapScale;mapY=vh/2-450*mapScale;applyMapTransform();}
export function bindMap(){renderMap();setTimeout(centerMap,300);mapVp.addEventListener('touchstart',e=>{if(e.touches.length===2){pinch=true;pd0=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);ps0=mapScale;}else{mdrag=true;mlx=e.touches[0].clientX;mly=e.touches[0].clientY;}},{passive:true});mapVp.addEventListener('touchmove',e=>{if(pinch&&e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);mapScale=Math.max(0.35,Math.min(1.4,ps0*d/pd0));applyMapTransform();}else if(mdrag){const dx=e.touches[0].clientX-mlx,dy=e.touches[0].clientY-mly;mapX+=dx;mapY+=dy;mlx=e.touches[0].clientX;mly=e.touches[0].clientY;applyMapTransform();}},{passive:true});mapVp.addEventListener('touchend',e=>{if(e.touches.length===0){mdrag=false;pinch=false;}},{passive:true});}