import { S } from './state.js';
const RANKS=[['Spark','✦',0],['Neuron','◉',150],['Synapse','⌁',350],['Circuit','◇',650],['Cortex','⬡',1050],['Hemisphere','◐',1600],['Architect','△',2300],['Polymath','✺',3200],['Overmind','◆',4400],['BrainMax','♛',6000]];
const LABELS={state:'State Engine',spatial:'Spatial Forge',math:'Math Strategy',switching:'Rule Lab',episodic:'Episodic Worlds',inhibition:'Inhibition Lab',creativity:'Creative Forge',dual:'Dual Task'};
const isoDay=(d=new Date())=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
function rank(){let index=0;RANKS.forEach((r,i)=>{if(S.cq>=r[2])index=i});const now=RANKS[index],next=RANKS[index+1],pct=next?Math.min(100,(S.cq-now[2])/(next[2]-now[2])*100):100;return{index,now,next,pct};}
function sessions(){return S.lab?.sessions||[];}
function render(){const root=document.getElementById('progressRoot');if(!root)return;const r=rank(),all=sessions(),today=isoDay(),todaySessions=all.filter(x=>isoDay(x.at)===today),skills=Object.entries(S.skills||{}).sort((a,b)=>b[1].rating-a[1].rating),days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=isoDay(d);return{label:d.toLocaleDateString(undefined,{weekday:'narrow'}),count:all.filter(x=>isoDay(x.at)===key).length,today:key===today}}),max=Math.max(1,...days.map(x=>x.count));root.innerHTML=`<div class="progress-head"><div class="progress-kicker">Adaptive mastery</div><div class="progress-title">Progress</div><div class="progress-sub">Ratings rise only when accuracy, speed and challenge stay aligned.</div></div><section class="rank-card"><div class="rank-row"><div class="rank-mark">${r.now[1]}</div><div class="rank-copy"><div class="rank-label">Current rank</div><div class="rank-name">${r.now[0]}</div><div class="rank-division">${S.cq.toLocaleString()} CQ</div></div></div><div class="rank-meter"><div class="rank-meta"><span>${r.next?`${r.next[2]-S.cq} CQ to ${r.next[0]}`:'Maximum rank'}</span><span>${Math.round(r.pct)}%</span></div><div class="rank-track"><div class="rank-fill" style="width:${r.pct}%"></div></div></div></section><div class="metric-grid"><div class="metric-card"><div class="metric-value">${todaySessions.length}</div><div class="metric-label">Sessions today</div></div><div class="metric-card"><div class="metric-value">${S.bestAcc||0}%</div><div class="metric-label">Best accuracy</div></div></div><section class="best-card"><div class="section-row"><div class="section-name">Skill ratings</div><div class="section-note">Infinite scale</div></div><div class="best-list">${skills.map(([key,s])=>{const delta=s.history?.at(-1)?.delta||0;return`<div class="best-row"><i class="best-dot"></i><span class="best-name">${LABELS[key]||key}<small style="display:block;color:var(--text-3)">${s.sessions||0} sessions · peak ${Math.round(s.peak||s.rating)}</small></span><strong class="best-score">${Math.round(s.rating)} <small style="color:${delta>=0?'var(--lav)':'var(--text-3)'}">${delta>=0?'+':''}${delta}</small></strong></div>`}).join('')}</div></section><section class="week-card"><div class="section-row"><div class="section-name">Last 7 days</div><div class="section-note">${days.reduce((n,d)=>n+d.count,0)} sessions</div></div><div class="week-bars">${days.map(d=>`<div class="day-col ${d.today?'today':''}"><div class="day-bar" style="height:${Math.max(5,d.count/max*58)}px"></div><div class="day-label">${d.label}</div></div>`).join('')}</div></section><details class="science-pocket"><summary>How difficulty works</summary><p>There is no final level. Rating controls several dimensions at once: memory span, rule count, interference, novelty and only then response time. The target band is 70–85% accuracy.</p></details>`;}
function init(){render();document.querySelector('.tab[data-v="4"]')?.addEventListener('click',render);window.addEventListener('skill:updated',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
