import { S } from './state.js';

const STORE='bmx_progress_v1';
const RANKS=[
 {name:'Spark',icon:'✦',at:0,color:'oklch(80% .11 300)'},
 {name:'Neuron',icon:'◉',at:150,color:'oklch(78% .13 292)'},
 {name:'Synapse',icon:'⌁',at:350,color:'oklch(76% .15 305)'},
 {name:'Circuit',icon:'◇',at:650,color:'oklch(75% .14 280)'},
 {name:'Cortex',icon:'⬡',at:1050,color:'oklch(78% .13 320)'},
 {name:'Hemisphere',icon:'◐',at:1600,color:'oklch(80% .12 270)'},
 {name:'Architect',icon:'△',at:2300,color:'oklch(82% .13 85)'},
 {name:'Polymath',icon:'✺',at:3200,color:'oklch(82% .14 55)'},
 {name:'Overmind',icon:'◆',at:4400,color:'oklch(80% .16 340)'},
 {name:'BrainMax',icon:'♛',at:6000,color:'oklch(88% .14 95)'}
];
const GAMES={rotation:'Mental Rotation',math:'Adaptive Math',memory:'Memory Sequence',stroop:'Stroop Focus',creative:'Creative Flow',critical:'Critical Thinking',dual:'Dual N-Back'};
const isoDay=(date=new Date())=>{const d=new Date(date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
function loadLog(){try{return JSON.parse(localStorage.getItem(STORE))||[]}catch{return[]}}
function saveLog(log){localStorage.setItem(STORE,JSON.stringify(log.slice(-180)))}
function rankState(){const cq=Math.max(0,Number(S.cq)||0);let index=0;RANKS.forEach((r,i)=>{if(cq>=r.at)index=i});const rank=RANKS[index],next=RANKS[index+1];const span=next?next.at-rank.at:1;const inside=next?cq-rank.at:span;const division=Math.max(1,3-Math.floor(Math.min(.999,inside/span)*3));return{cq,index,rank,next,pct:next?Math.max(0,Math.min(100,inside/span*100)):100,division};}
function render(){const root=document.getElementById('progressRoot');if(!root)return;const rs=rankState(),log=loadLog(),today=isoDay();const todayEntries=log.filter(x=>x.day===today);const todayBest=todayEntries.length?Math.max(...todayEntries.map(x=>x.acc)):null;const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=isoDay(d);return{key,label:d.toLocaleDateString(undefined,{weekday:'narrow'}),count:log.filter(x=>x.day===key).length,today:key===today}});const maxDay=Math.max(1,...days.map(x=>x.count));const best=Object.entries(S.best||{}).filter(([,v])=>Number(v)>0).sort((a,b)=>b[1]-a[1]).slice(0,5);const nextText=rs.next?`${Math.max(0,rs.next.at-rs.cq)} CQ to ${rs.next.name}`:'Maximum rank reached';root.style.setProperty('--rank-color',rs.rank.color);root.innerHTML=`
 <div class="progress-head"><div class="progress-kicker">Personal progression</div><div class="progress-title">Progress</div><div class="progress-sub">Beat your baseline. Ranks reward consistency, not one lucky run.</div></div>
 <section class="rank-card"><div class="rank-row"><div class="rank-mark">${rs.rank.icon}</div><div class="rank-copy"><div class="rank-label">Current rank</div><div class="rank-name">${rs.rank.name}</div><div class="rank-division">DIVISION ${['I','II','III'][rs.division-1]}</div></div></div><div class="rank-meter"><div class="rank-meta"><span>${rs.cq.toLocaleString()} CQ</span><span>${nextText}</span></div><div class="rank-track"><div class="rank-fill" style="width:${rs.pct}%"></div></div></div></section>
 <div class="metric-grid"><div class="metric-card"><div class="metric-value">${todayBest===null?'--':todayBest+'%'}</div><div class="metric-label">Best today</div></div><div class="metric-card"><div class="metric-value">${Number(S.bestAcc)||0}%</div><div class="metric-label">All-time accuracy</div></div><div class="metric-card"><div class="metric-value">${Number(S.sessions)||0}</div><div class="metric-label">Sessions completed</div></div><div class="metric-card"><div class="metric-value">${Number(S.records)||0}</div><div class="metric-label">Records broken</div></div></div>
 <section class="week-card"><div class="section-row"><div class="section-name">Last 7 days</div><div class="section-note">${days.reduce((n,d)=>n+d.count,0)} sessions</div></div><div class="week-bars">${days.map(d=>`<div class="day-col ${d.today?'today':''}"><div class="day-bar" style="height:${Math.max(5,d.count/maxDay*58)}px"></div><div class="day-label">${d.label}</div></div>`).join('')}</div></section>
 <section class="best-card"><div class="section-row"><div class="section-name">Personal bests</div><div class="section-note">Accuracy</div></div><div class="best-list">${best.length?best.map(([k,v])=>`<div class="best-row"><i class="best-dot"></i><span class="best-name">${GAMES[k]||k}</span><strong class="best-score">${v}%</strong></div>`).join(''):'<div class="progress-sub">Complete a session to set your first baseline.</div>'}</div></section>
 <section class="rank-road"><div class="section-row"><div class="section-name">Rank path</div><div class="section-note">10 ranks · 3 divisions each</div></div><div class="rank-strip">${RANKS.map((r,i)=>`<div class="rank-chip ${i<rs.index?'reached':''} ${i===rs.index?'current':''}"><div class="rank-chip-icon">${r.icon}</div><div class="rank-chip-name">${r.name}</div></div>`).join('')}</div></section>
 <details class="science-pocket"><summary>Science behind your training</summary><p>Short, adaptive practice works best when feedback is immediate and difficulty stays near your edge. The library now appears here as context instead of competing with training in the main navigation.</p></details>`;}
function captureResult(){const body=document.getElementById('gameBody');if(!body)return;const text=body.textContent||'';if(!/Finish session/i.test(text))return;const match=text.match(/(\d+)%\s*Accuracy/i);if(!match)return;const acc=Number(match[1]),session=Number(S.sessions)||0;const log=loadLog();const signature=`${isoDay()}:${session}:${acc}`;if(log.some(x=>x.signature===signature))return;log.push({day:isoDay(),acc,session,signature,at:Date.now()});saveLog(log);render();}
function init(){render();document.querySelector('.tab[data-v="4"]')?.addEventListener('click',render);const body=document.getElementById('gameBody');if(body)new MutationObserver(captureResult).observe(body,{childList:true,subtree:true,characterData:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
